#include "credentials.h"

// Code generated by Arduino IoT Cloud
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]               = WIFI_SSID;    // Network SSID (name)
const char PASS[]               = WIFI_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBrightnessChange();

CloudDimmedLight brightness;

void initProperties(){
  ArduinoCloud.addProperty(brightness, READWRITE, ON_CHANGE, onBrightnessChange, 1);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
